### ISSUE TITLE
train fails with LJSpeech-1.1

### ISSUE THREAD

**Issue by igorsitdikov** [rhasspy/larynx2#10]
When run train it fails with error
    assert utt.speaker_id is not None, "Missing speaker id"
AssertionError: Missing speaker id
I thought that it should work on dataset which you've added in README.
dataset was prepared with scripts which is provided in README.

**Comment by synesthesiam** [comment]
I think there was a bug in the preprocessing script that should be fixed. Try editing your `config.json` file and changing `num_speakers` to 1.

**Comment by igorsitdikov** [comment]
Thank you, it works.
Is there way to continue train from checkpoint? could you please provide command?

**Comment by synesthesiam** [comment]
Yes, add `--resume_from_checkpoint <path>` to the training command. You can see all of the options with `--help`

**Comment by igorsitdikov** [comment]
Thanks a lot!
