### ISSUE TITLE
Add English U.S. Voice

### ISSUE THREAD

**Issue by mush42** [rhasspy/larynx2#12]
Hi @synesthesiam 

Would it be possible to train a male voice for English using the following dataset:

https://www.kaggle.com/datasets/roholazandie/ryanspeech

I don't know the usage terms of this dataset.

Best
Musharraf

**Comment by mush42** [comment]
Thanks For adding the Ryan Speech Voice.

This is going to be a game changer for blind people. I'm going to create an add-on for [NVDA Screen Reader](https://github.com/nvaccess/nvda) to make this awesome TTS technology available for blind users all over the world.

Best

**Comment by synesthesiam** [comment]
Thanks @mush42! Please let me know when you've created the add-on for NVDA. I've been hoping to do that for some time, but haven't had the time to spend on Windows.

**Comment by synesthesiam** [comment]
The voice has some audio crackling, so I will train it for a bit longer.

**Comment by synesthesiam** [comment]
Yeah, I can train a medium quality version too. I agree they sound way better, but are definitely slower on low-end hardware like a Pi 4.

**Comment by king-dahmanus** [comment]
Hey @mush42 , thanks for taking the initiative to port it to NVDA. I have some concerns though. How fast is it going to be on low-end hardware, such as a celeron n3060?

**Comment by mush42** [comment]
I have no idea.
Here in my notebook, which runs on an 11th gen core i7, the real time factor is around 3% which is pretty darn good.
We can try different onnxruntime optimizations, one of which is using the directML inference accelerator.

I don't think it will run slower than the raspberry pi in any modern Intel processor.

**Comment by king-dahmanus** [comment]
Any *modern* intel processor lol, mine isn't exactly what you would call Modern haha. Anyways the addon is worth a try when it comes out.
Off topic, do you have any way we could get in touch, like discord, reddit and the like? Just to make it fast, here's my discord: green_eye#3765
