### ISSUE TITLE
How to run with GPU

### ISSUE THREAD

**Issue by trunglebka** [rhasspy/larynx2#14]
Firstly, Thank for the high performance TTS tool.
I've tried with CPU and it is really fast, but I don't know how to run it with GPU to make it even faster.
Do this tool support GPU/Cuda?

**Comment by synesthesiam** [comment]
You're welcome! GPU support is possible, but not easy out of the box right now. Probably the "easiest" route would be to adapt the `infer_onnx.py` script in `src/python` to use Onnx's `CUDAExecutionProvider` via the [onnxruntime-gpu](https://pypi.org/project/onnxruntime-gpu/).

Another option is to recompile the C++ code with the CMake flags for CUDA support and use the [CUDA Execution Provider](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html).

Finally, the original model checkpoints can be run directly with PyTorch. I uploaded the generator checkpoint for the English voice if you want to try it out: https://github.com/rhasspy/larynx2/releases/download/v0.0.2/generator-en-us_blizzard_lessac.tar.gz

**Comment by trunglebka** [comment]
Thanks a lot!
