### ISSUE TITLE
Why can this program execute in a pure docker ubuntu container?

### ISSUE THREAD

**Issue by dzcmingdi** [rhasspy/larynx2#15]
Library `espeak-ng` includes other dependencies(like libsndfile,libpcaudio), I extract released files into a ubuntu 18.04 docker container and i don't do anything,just execute it,then no error happens.
Why?Can you tell me how do you build libespeak-ng?

**Comment by trunglebka** [comment]
Take a look at the Dockerfile: https://github.com/rhasspy/larynx2/blob/master/Dockerfile#L18

**Comment by dzcmingdi** [comment]
> Take a look at the Dockerfile: https://github.com/rhasspy/larynx2/blob/master/Dockerfile#L18

ok,thanks.I see.

**Comment by dzcmingdi** [comment]
can you give me all train checkpoints?

**Comment by synesthesiam** [comment]
@dzcmingdi Sure, they are available here: https://drive.google.com/drive/folders/1PXz72f_R98j9-iXtYxMJCePICAwRXa3z?usp=sharing

**Comment by dzcmingdi** [comment]
thanks

**Comment by dzcmingdi** [comment]
> @dzcmingdi Sure, they are available here: https://drive.google.com/drive/folders/1PXz72f_R98j9-iXtYxMJCePICAwRXa3z?usp=sharing

thanks
