### ISSUE TITLE
What is the reason for unsqueezing audio in export_onnx.py script?

### ISSUE THREAD

**Issue by trunglebka** [rhasspy/larynx2#18]
Hi, I'm diving in to larynx2 and encoutered inconsistence in shape of audio generated by torch and onnx scripts.

In infer_generator.py, audio shape is something like: `(1, 1, 413696)` and I interpret it as `(batch, channels, samples)` (isn't it?)

In infer_onnx.py, audio shape is something like: `(1, 1, 1, 421376)` - I'm unable to interpret it anymore, so I've looked into the exporting script and saw below line. Can you help me to understand the reason for unsqueezing audio in this script?

https://github.com/rhasspy/larynx2/blob/acc3068176feb18f399b95502e7ea5ad01ed6275/src/python/larynx_train/export_onnx.py#L67

And since the `time` axe of output  is `2`, I wonder if this is a mistake?
https://github.com/rhasspy/larynx2/blob/acc3068176feb18f399b95502e7ea5ad01ed6275/src/python/larynx_train/export_onnx.py#L99

larynx2 version: latest 25f3f89 commit

**Comment by synesthesiam** [comment]
Looking at it now, I actually don't remember why I did this :laughing: 

I think was trying to match the expectations of a different program for running the Onnx model at the time, but I ended up just writing it myself in the end. So this appears to be unnecessary now.
