### ISSUE TITLE
error on execution

### ISSUE THREAD

**Issue by nfaraji2002** [rhasspy/larynx2#3]
Hi,

Thanks for your awesome library.
I have executed this line on RPI 4 (buster 64bit-debian 10) after downloading a model:
echo 'Welcome to the world of speech synthesis!' | \
  ./larynx --model blizzard_lessac-medium.onnx --output_file welcome.wav

but there is a error relating to GLIBC as follows:
./larynx: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/pi/speech/larynx/larynx/libespeak-ng.so.1)

I tried to upgrade my GLIBC from 2.28 to 2.29, but I could not find this version in this website: https://packages.debian.org/buster/

How can I solve the issue?
Best,

**Comment by synesthesiam** [comment]
Larynx 2 is built on Debian bullseye, which has a newer GLIBC. You will need to build from source on buster, which I found to be a major pain because `gcc` was out of date (no C++20).

If any C++ wizard could help out here, it would be much appreciated.

**Comment by synesthesiam** [comment]
FYI, I re-built the Larynx binaries on an older Linux distro with GLIBC 2.20. Please re-download and try again.
