### ISSUE TITLE
issue on training

### ISSUE THREAD

**Issue by nfaraji2002** [rhasspy/larynx2#4]
hi,
another issue is in training:
ModuleNotFoundError: No module named 'larynx_train.vits.monotonic_align.monotonic_align'
Thanks for your help to resolve this issue.

**Comment by synesthesiam** [comment]
Forgot to mention in the docs, try running the `build_monotonic_align.sh` script in `src/python`

**Comment by nfaraji2002** [comment]
Thanks for your reply. 
I will try this solution.

**Comment by alirezainallo** [comment]
> Forgot to mention in the docs, try running the `build_monotonic_align.sh` script in `src/python`
i try it but even get this error
