### ISSUE TITLE
LJspeech Checkpoint for fine-tuning

### ISSUE THREAD

**Issue by Muhammad-Abdelsattar** [rhasspy/larynx2#5]
I wonder if there's a checkpoint from the pre-trained model (LJspeech dataset) to continue training from. That would greatly save time and computation especially for low resource datasets.

**Comment by synesthesiam** [comment]
Are you interested in 22Khz or 16Khz output?

**Comment by Muhammad-Abdelsattar** [comment]
> Are you interested in 22Khz or 16Khz output?
 22khz.

**Comment by Muhammad-Abdelsattar** [comment]
22khz.

**Comment by synesthesiam** [comment]
OK, I'll see what checkpoints I have available.

**Comment by Muhammad-Abdelsattar** [comment]
@synesthesiam Thanks. BTW both 22khz and 16khz will be useful.

**Comment by Muhammad-Abdelsattar** [comment]
@synesthesiam Any updates ?

**Comment by synesthesiam** [comment]
I will have to train these from scratch, unfortunately. I've started on the 22Khz and will get the 16Khz started. Should be a few days :+1:

**Comment by synesthesiam** [comment]
I ran into a problem with training and lost a few days. But I'm back on track now, with the 22Khz model on epoch 527 and the 16Khz model on epoch 1165.

I'll let them run over the weekend and see how they do. Listening to them, the speech is still a little shaky. If you'd like the early checkpoints, I can send them along.

**Comment by nefastosaturo** [comment]
hey @synesthesiam thanks for your hard work. Waiting for some checkpoints to start some finetuning. I'm considering doing some training for the italian language starting from the U.S. English 16khz model and see how it goes :)

**Comment by synesthesiam** [comment]
Here is the current 16Khz checkpoint (epoch 3279): https://drive.google.com/drive/folders/16-IqysAkR3uoawiW8NDBv74uAGECaAxl?usp=share_link

It's not completely "finished" yet (had some hardware issues), but it's probably far enough along for you to use. Make sure to use the same model parameters I have in `train.sh`. In addition to using the lower 16Khz sampling rate, I modified other parameters to speed inference up.
