### ISSUE TITLE
issue on training

### ISSUE THREAD

**Issue by nfaraji2002** [rhasspy/larynx2#6]
Dear Michael,
Thanks for the reply. Which Debian bullseye did you use for test? 64 bit or 32 bit?
Also, I want to train Larynx 2 on  a Ubuntu 18.04. Is the training procedure the same as you said in your post?

**Comment by synesthesiam** [comment]
I have only trained on 64-bit Debian bullseye using Docker and an NVIDIA GPU. The procedure should be the same on Ubuntu 18.04 if you have an up to date Docker install.

**Comment by nfaraji2002** [comment]
Thanks. I do not have any experiences using Docker. I just have a computer with GPU, and I do not know how I can use a raspberry pi 4 with a Gpu for training a big model. Up to now, I have just used RPI 4 for evaluation not training. I always train a model on a computer with GPU and then bring the trained model on RPI for test. If it is possible,  a recipe for training on ubuntu without docker can be so beneficial, OR, a link that you recommend for usage of dockers.

**Comment by synesthesiam** [comment]
I don't think it would be possible to use a Raspberry Pi for training this kind of model. It needs 8+ GB of GPU RAM in my experience just to get started.

I purposely don't train with CUDA outside Docker anymore because it almost always results in a broken system. Plus, it's almost impossible to get the right driver, CUDA version, and CUDA-DNN library all working together. I highly recommend starting with the included `Dockerfile`.

**Comment by nfaraji2002** [comment]
Thanks for the reply.
In inference phase, Larynx was executed on my raspberry pi 4 without any error. In training (the command below), I have encountered another error in Ubuntu 18.04:
python3 -m larynx_train  --dataset-dir /home/dl/Desktop/ZahraAmini/TTSlarynx/persian --accelerator 'gpu' --devices 1  --batch-size 16 --validation-split 0.05 --num-test-examples 4  --max_epochs 1000 --precision 32

it runs for some epochs and then :
RuntimeError: The expanded size of the tensor (8192) must match the existing size (7744) at non-singleton dimension 1.  Target sizes: [1, 8192].  Tensor sizes: [7744]

One time, I encountered this error at epoch 133. Another run at epoch 30 and so on. In fact, this error happens in different epochs in different runs

**Comment by synesthesiam** [comment]
I've seen this before when I have at least one audio file that's too small or has a very wrong transcription. Try sorting the cached `.pt` files by size and look for ones that are way smaller than the others.

**Comment by nfaraji2002** [comment]
Thanks again

**Comment by nfaraji2002** [comment]
Another question: Is 1000 epochs enough for training on 1-hour data? 
What do you recommend for the final loss after training? The loss in the first epoch of my train is about 30, but it does not get smaller than 15 after epoch 100. I think the loss have been saturated. What is your idea?

**Comment by nfaraji2002** [comment]
another issue!
I can not export my checkpoint to onnx. when I execute the command below :
python3 -m larynx_train.export_onnx checkpoint  ./lightning_logs/version_13/checkpoints/epoch=999-step=860000.ckpt output ./model.onnx

this error happens : 
export_onnx.py: error: unrecognized arguments: output ./model.onnx

**Comment by synesthesiam** [comment]
Try removing "output":

`python3 -m larynx_train.export_onnx checkpoint ./lightning_logs/version_13/checkpoints/epoch=999-step=860000.ckpt ./model.onnx`

**Comment by synesthesiam** [comment]
> Another question: Is 1000 epochs enough for training on 1-hour data? What do you recommend for the final loss after training? The loss in the first epoch of my train is about 30, but it does not get smaller than 15 after epoch 100. I think the loss have been saturated. What is your idea?

I usually watch the discriminator loss (`loss_disc_all`). That seems to go down much slower than the generator loss (`loss_gen_all`), and has more impact on the fine details of the voice.

1000 epochs is probably fine if you only have an hour's worth of data. Did you fine-tune an existing model or train from scratch?

**Comment by nfaraji2002** [comment]
Thanks. I train from scratch.
