### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cmc2023** [rhasspy/larynx2#8]
Hi, thanks for your great job!  But when I trained the model with V100 GPU, I encountered such error message:

RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0; 15.90 GiB total capacity; 13.66 GiB already allocated; 236.75 MiB free; 14.58 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Then I changed the batch size value to 16, 8 , 4 and even 1,  the message still issued. 
Can you check this error?

**Comment by synesthesiam** [comment]
I see this sometimes if I have data with a few really long sentences. Try setting `--max-phoneme-ids` to something like 200-400, and see if that helps.

**Comment by cmc2023** [comment]
> I see this sometimes if I have data with a few really long sentences. Try setting `--max-phoneme-ids` to something like 200-400, and see if that helps.

Thank you for your reply, it works!  Another question, how to train the model with multi-GPUs? I tried to train it on 4 GPUs and set "CUDA_VISIBLE_DEVICES=0,1,2,3" before the common line, but only one GPU ran for training.

**Comment by synesthesiam** [comment]
Change `--devices 1` in the `train.sh` to use more than one GPU. I'm using PyTorch Lightning, so I'm hoping multi-GPU works out of the box.

**Comment by cmc2023** [comment]
Got it, thanks!

**Comment by orkars** [comment]
Do you know the default value of --max-phoneme-ids ?
